"""init schema

Revision ID: 1712be522354
Revises: 
Create Date: 2026-05-11 12:36:30.681644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1712be522354'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=128), nullable=False),
    sa.Column('vehicle', sa.String(length=64), nullable=True),
    sa.Column('plate', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('intake_mode', sa.String(length=16), nullable=False),
    sa.Column('intake_box_qty', sa.Integer(), nullable=True),
    sa.Column('photo_required', sa.Boolean(), nullable=False),
    sa.Column('mark_required', sa.Boolean(), nullable=False),
    sa.Column('size_json', sa.JSON(), nullable=True),
    sa.Column('photo_paths_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skus_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_skus_barcode'), ['barcode'], unique=True)

    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=8), nullable=False),
    sa.Column('warehouse', sa.String(length=128), nullable=False),
    sa.Column('mp_supply_id', sa.String(length=64), nullable=True),
    sa.Column('slot_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_kind', sa.String(length=32), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('parsed_payload_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_sku_id', sa.Integer(), nullable=False),
    sa.Column('component_sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kit_sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_sku_id', 'component_sku_id', name='uq_kit_component')
    )
    with op.batch_alter_table('sku_kits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_kits_kit_sku_id'), ['kit_sku_id'], unique=False)

    op.create_table('state_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('event_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_log_supply_id'), ['supply_id'], unique=False)

    op.create_table('stock_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_snapshots_sku_id'), ['sku_id'], unique=False)

    op.create_table('supply_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty_planned', sa.Integer(), nullable=False),
    sa.Column('qty_picked', sa.Integer(), nullable=True),
    sa.Column('qty_accepted', sa.Integer(), nullable=True),
    sa.Column('box_label', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('expanded_from_kit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expanded_from_kit_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_items_supply_id'), ['supply_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_items_supply_id'))

    op.drop_table('supply_items')
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_sku_id'))

    op.drop_table('stock_snapshots')
    with op.batch_alter_table('state_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_log_supply_id'))

    op.drop_table('state_log')
    with op.batch_alter_table('sku_kits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_kits_kit_sku_id'))

    op.drop_table('sku_kits')
    op.drop_table('inbox_files')
    op.drop_table('supplies')
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skus_barcode'))
        batch_op.drop_index(batch_op.f('ix_skus_article'))

    op.drop_table('skus')
    op.drop_table('drivers')
    # ### end Alembic commands ###
