"""add target_dates_json

Revision ID: 1d4b0ab4021c
Revises: d5f81b2a9c44
Create Date: 2026-05-13 09:34:00.995043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d4b0ab4021c'
down_revision: Union[str, None] = 'd5f81b2a9c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_dates_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_requests', schema=None) as batch_op:
        batch_op.drop_column('target_dates_json')

    # ### end Alembic commands ###
