"""add target_hours_json to shipment_request

Revision ID: 390d74561795
Revises: 86b1ae89042f
Create Date: 2026-05-14 13:44:41.422422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '390d74561795'
down_revision: Union[str, None] = '86b1ae89042f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_hours_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_requests', schema=None) as batch_op:
        batch_op.drop_column('target_hours_json')

    # ### end Alembic commands ###
