"""add drop_off_warehouse_name to ozon_drafts

Revision ID: 4942066afe35
Revises: 724b68d0a132
Create Date: 2026-05-14 08:22:05.603333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4942066afe35'
down_revision: Union[str, None] = '724b68d0a132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ozon_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_off_warehouse_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ozon_drafts', schema=None) as batch_op:
        batch_op.drop_column('drop_off_warehouse_name')

    # ### end Alembic commands ###
