"""ozon_products and wb_products separation

Revision ID: 724b68d0a132
Revises: b39bace394a5
Create Date: 2026-05-14 07:06:13.004828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '724b68d0a132'
down_revision: Union[str, None] = 'b39bace394a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(length=128), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('barcode_primary', sa.String(length=64), nullable=True),
    sa.Column('raw_barcodes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ozon_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ozon_products_barcode_primary'), ['barcode_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_ozon_products_offer_id'), ['offer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ozon_products_sku'), ['sku'], unique=False)

    op.create_table('wb_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('barcode_primary', sa.String(length=64), nullable=True),
    sa.Column('raw_barcodes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wb_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wb_products_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_wb_products_barcode_primary'), ['barcode_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_wb_products_nm_id'), ['nm_id'], unique=True)

    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ozon_product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wb_product_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shipment_items_ozon_product_id'), ['ozon_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_items_wb_product_id'), ['wb_product_id'], unique=False)
        batch_op.create_foreign_key('fk_shipment_items_ozon_product_id', 'ozon_products', ['ozon_product_id'], ['id'])
        batch_op.create_foreign_key('fk_shipment_items_wb_product_id', 'wb_products', ['wb_product_id'], ['id'])

    # === Data migration: переносим Sku → ozon_products / wb_products ===
    # Учитываем что в старой схеме могли быть дубли (один offer_id на 2+ Sku) —
    # для каждого уникального offer_id оставляем первую запись.
    conn = op.get_bind()

    sku_rows = conn.execute(sa.text(
        "SELECT id, barcode, article, name, ozon_offer_id, ozon_sku, wb_nm_id FROM skus"
    )).mappings().all()

    sku_to_ozon: dict = {}   # sku.id → ozon_products.id
    sku_to_wb: dict = {}     # sku.id → wb_products.id
    offer_to_oz_id: dict = {}  # offer_id → ozon_products.id (для dedup)
    nm_to_wb_id: dict = {}     # nm_id → wb_products.id

    for r in sku_rows:
        if r["ozon_offer_id"]:
            offer = r["ozon_offer_id"]
            if offer in offer_to_oz_id:
                sku_to_ozon[r["id"]] = offer_to_oz_id[offer]
            else:
                res = conn.execute(sa.text(
                    "INSERT INTO ozon_products "
                    "(offer_id, sku, name, barcode_primary, created_at, updated_at) "
                    "VALUES (:offer, :sku, :name, :bc, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                ), {
                    "offer": offer,
                    "sku": r["ozon_sku"],
                    "name": r["name"],
                    "bc": r["barcode"],
                })
                offer_to_oz_id[offer] = res.lastrowid
                sku_to_ozon[r["id"]] = res.lastrowid
        if r["wb_nm_id"]:
            nm = r["wb_nm_id"]
            if nm in nm_to_wb_id:
                sku_to_wb[r["id"]] = nm_to_wb_id[nm]
            else:
                res = conn.execute(sa.text(
                    "INSERT INTO wb_products "
                    "(nm_id, article, name, barcode_primary, created_at, updated_at) "
                    "VALUES (:nm, :art, :name, :bc, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                ), {
                    "nm": nm,
                    "art": r["article"],
                    "name": r["name"],
                    "bc": r["barcode"],
                })
                nm_to_wb_id[nm] = res.lastrowid
                sku_to_wb[r["id"]] = res.lastrowid

    # Привязываем shipment_items: sku_id → ozon_product_id/wb_product_id по marketplace
    items = conn.execute(sa.text(
        "SELECT id, sku_id, marketplace FROM shipment_items WHERE sku_id IS NOT NULL"
    )).mappings().all()
    for it in items:
        mp = (it["marketplace"] or "").lower()
        sku_id = it["sku_id"]
        if mp == "ozon" and sku_id in sku_to_ozon:
            conn.execute(sa.text(
                "UPDATE shipment_items SET ozon_product_id=:pid WHERE id=:id"
            ), {"pid": sku_to_ozon[sku_id], "id": it["id"]})
        elif mp == "wb" and sku_id in sku_to_wb:
            conn.execute(sa.text(
                "UPDATE shipment_items SET wb_product_id=:pid WHERE id=:id"
            ), {"pid": sku_to_wb[sku_id], "id": it["id"]})

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shipment_items_wb_product_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_items_ozon_product_id'))
        batch_op.drop_column('wb_product_id')
        batch_op.drop_column('ozon_product_id')

    with op.batch_alter_table('wb_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wb_products_nm_id'))
        batch_op.drop_index(batch_op.f('ix_wb_products_barcode_primary'))
        batch_op.drop_index(batch_op.f('ix_wb_products_article'))

    op.drop_table('wb_products')
    with op.batch_alter_table('ozon_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ozon_products_sku'))
        batch_op.drop_index(batch_op.f('ix_ozon_products_offer_id'))
        batch_op.drop_index(batch_op.f('ix_ozon_products_barcode_primary'))

    op.drop_table('ozon_products')
    # ### end Alembic commands ###
