"""add ozon_supply_type to shipment_requests

Revision ID: 86b1ae89042f
Revises: 4942066afe35
Create Date: 2026-05-14 11:01:43.489051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86b1ae89042f'
down_revision: Union[str, None] = '4942066afe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ozon_supply_type', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_requests', schema=None) as batch_op:
        batch_op.drop_column('ozon_supply_type')

    # ### end Alembic commands ###
