"""add point_type to favorites

Revision ID: b39bace394a5
Revises: def8b4c90776
Create Date: 2026-05-13 11:49:16.868759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b39bace394a5'
down_revision: Union[str, None] = 'def8b4c90776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_crossdock_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_crossdock_points', schema=None) as batch_op:
        batch_op.drop_column('point_type')

    # ### end Alembic commands ###
