"""ozon_drafts and favorite_crossdock_points

Revision ID: def8b4c90776
Revises: 1d4b0ab4021c
Create Date: 2026-05-13 11:23:09.227182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'def8b4c90776'
down_revision: Union[str, None] = '1d4b0ab4021c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_crossdock_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ozon_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.String(length=64), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('supply_type', sa.Integer(), nullable=False),
    sa.Column('drop_off_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['shipment_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ozon_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ozon_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ozon_drafts_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ozon_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ozon_drafts_request_id'))
        batch_op.drop_index(batch_op.f('ix_ozon_drafts_created_at'))

    op.drop_table('ozon_drafts')
    op.drop_table('favorite_crossdock_points')
    # ### end Alembic commands ###
